name: Required pull request labels

on:
  pull_request:
    branches:
      - main
    
jobs:
  enforce-labels:
    runs-on: ubuntu-22.04
    steps:
    - uses: mheap/github-action-required-labels@v3
      with:
        mode: exactly
        count: 1
        labels: "type::security, type::feature, type::bug, type::chore, type::docs"
